### ISSUE TITLE
peer review for hw07

### ISSUE THREAD

**Issue by QinxinLin** [STAT545-UBC-students/hw07-shreeramsenthi#1]
Coding style: Excellent
Coding strategy: Excellent
Achievement, mastery, cleverness, creativity: Excellent
Ease of access: Excellent
Graphs: Excellent
Tables: Excellent

Remark:

1. I was able to download and install your package without any problems
2. Functions are well documented with appropriate examples
3. Good work on unit testing, this was well done!
4. Your package includes six new functions, very useful for me. Actually, I learned a lot from your work, thank you. 
5. Excellent work overall, your package runs smoothly and is well implemented.

**Comment by shreeramsenthi** [comment]
Thanks for the kind feedback!
