### ISSUE TITLE
TA comments 

### ISSUE THREAD

**Issue by ChadFibke** [STAT545-UBC-students/hw07-shreeramsenthi#2]
# **Coding Style**

### *The good* :thumbsup:

* New functions are nicely annotated, and good looks great!

### *Needs work* :thumbsdown:

* NA

# **Coding Strategy**

### *The good* :thumbsup:

* The vignettes are linked in your package index! This helps to bundle the helpful information all in one place! :fire:

* Vignettes are informative! :star:

* Descriptions were mostly informative!

* Great use of the ellipsis "..." to prevent too much clutter in your documentation!

* Good use of in function checks. Using `stop()` in a conditional statements  provides users with informative error messages, and terminates the code!

* Filled out the description file with all relevant information! 

* Yay no fatal errors when I run `check()`. 

### *Needs work* :thumbsdown:

* Try exploring new roxygen2 `@` to add more informative function descriptions. Adding `@examples` into your R script that holds your new functions can add an additional section at the bottom of your function documentation! This well help with usability!

* When you make reverence to the ANOVA args you should also provide a link to the anova description page. This will help the user navigate more efficiently!

* It would be a good idea to use `@importFrom purrr map` to allow your package to use the map function from the purr package. Or even write a `require(package name)` in your code instead of using   purrr::map. I think the use of purrr::map causes are to install all the dependencies. The `@` will communicate this package dependency to the documentation and namespace file, and should resolve your issue!

* Your `check_models()` seems like an external function used in summarize_models, which you do not have to export. 

* It may also be useful to provide a simple dataset that people can test on to validate that your function is also working on their data!

# **Graphs & Tables**

### *The good* :thumbsup:

* NA

### *Needs work* :thumbsdown:

* NA

# **Creativity & Ease of Access**

### *The good* :thumbsup:

* Easy navigation from canvas to your repo.

* The README is populated with informative details about installation!

* Made your own functions and made your own package :fire:

### *Needs work* :thumbsdown:

* The README should explain how to install (which you do) *but* you should also include a selling point! Why is your package better than using base r, and it should include some examples!

* Also, give your package an informative name in so people who are searching for a package for multiple comparisons can easily find it! I had to hunt the package name down in the description file/found a random package name once I installed your package!

**Comment by ChadFibke** [comment]
Sorry reference not reverence!

**Comment by shreeramsenthi** [comment]
Hey Chad,

Thanks for the crazy detailed feedback! I guess we won't be making another package in this class, but I'll be sure to keep your comments in mind the next time I work on this stuff, thanks!

Cheers,
Shree
