### ISSUE TITLE
Peer Review 07

### ISSUE THREAD

**Issue by aidanh14** [STAT545-UBC-students/hw07-shreeramsenthi#3]
Peer Review for @shreeramsenthi 

----------------------------------------------------
Topic                       | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style**            | :heavy_check_mark: |  |  |
**Coding strategy**         |  :heavy_check_mark: |  |  |
**Presentation: graphs**    | :heavy_check_mark: |  |  |
**Presentation: tables**    |  :heavy_check_mark: |  |  |
**Achievement, creativity** | :heavy_check_mark: |  |  |
**Ease of access**          | :heavy_check_mark: |  |  |

Notes:

- Great creativity with breaking away from the original task!
- After installing/updating the dependencies mentioned, package installed without issue
- The linked vignette does a great job of showing the capabilities of the package, minimal and clean tables all the way through

Very impressed, keep up the good work! 👍

**Comment by shreeramsenthi** [comment]
Thanks for the kind feedback!
